name: CI/CD

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android
    env:
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ANDROID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "19"
          cache: "gradle"
      - run: ./gradlew clean build --parallel --no-daemon

      - name: Run unit tests
        run: ./gradlew test --parallel

      - name: Assemble Android Instrumentation Tests
        run: ./gradlew assembleDebugAndroidTest --parallel

      - name: Sonarqube analyze
        run: ./gradlew sonar --parallel

      - name: Firebase App Distribute
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/Android/secret/google_auth_cred.json
          GOOGLE_APPLICATION_CREDENTIALS_VALUE: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_VALUE}}
        run: ./scripts/config_google_auth_file.sh && ./gradlew release
        working-directory: ./Android
