name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SonarApp
    env:
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Angular build
        working-directory: ./AngularSonar
        run: |
          npm install
          npm run build

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build with Gradle and assemble debug APk
        run: ./gradlew assembleDebug --stacktrace

      - name: Run unit tests
        run: ./gradlew test

      - name: Assemble Android Instrumentation Tests
        run: ./gradlew assembleDebugAndroidTest

      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: SonarApp/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: SonarApp/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

      - name: Firebase App Distribute
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_PATH}}
          GOOGLE_APPLICATION_CREDENTIALS_VALUE: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_VALUE}}
        run: ./scripts/config_google_auth_file.sh && ./gradlew assembleRelease appDistributionUploadRelease
        working-directory: ./SonarApp
