name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SonarApp
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle and assemble debug APk
        run: ./gradlew assembleDebug --stacktrace
      - name: Run unit tests
        run: ./gradlew test 
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: SonarApp/app/build/outputs/apk/debug/app-debug.apk
#      - name: Upload Android Test APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-debug-androidTest
#          path: SonarApp/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SonarApp
    steps:
      - uses: actions/checkout@v1
      - name: Firebase App Distribute
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./gradlew assembleRelease
        #appDistributionUploadRelease
